server:
  port: 8012

spring:
  application:
    name: cloud-consumer-order8012

eureka:
  client:
    register-with-eureka: true # 是否要注册到配置中心
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7011/eureka